name: Test find_lowest_number.py
on: [push]
jobs:
  test_find_lowest_number:
    name: Test find_lowest_number.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
            python-version: '3.13.1'

      - name: Run test case 1 (file with 10 numbers)
        run: |
            python3 find_lowest_number.py test_data/test1_input.txt output1.txt
            diff output1.txt test_data/test1_expected.txt

      - name: Run test case 2 (file with 1 number)
        run: |
            python3 find_lowest_number.py test_data/test2_input.txt output2.txt
            diff output2.txt test_data/test2_expected.txt

      - name: Run test case 3 (file with no numbers)
        run: |
            python3 find_lowest_number.py test_data/test3_input.txt output3.txt
            diff output3.txt test_data/test3_expected.txt
